name: tmdb_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.2
  json_annotation: ^4.4.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/logo.png
    - assets/imgs/twitter_profile.jpg
    - assets/imgs/divider.png
    - assets/imgs/flags/ukraine_flag.jpg
    - assets/imgs/flags/gb_flag.png
    - assets/imgs/flags/spanish_flag.png
    - assets/imgs/flags/polish_flag.png
    - assets/imgs/flags/r_flag.png
  fonts:
    - family: Handjet
      fonts:
        - asset: assets/fonts/Handjet.ttf
    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf